default_language_version:
  python: python3.13

repos:
  # Ruff formatting and linting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.1
    hooks:
      - id: ruff-format
        name: Ruff Format
        description: Run ruff formatter

      - id: ruff
        name: Ruff Linter
        description: Run ruff linter
        args: [--fix, --exit-non-zero-on-fix]

  # wemake-python-styleguide
  - repo: https://github.com/wemake-services/wemake-python-styleguide
    rev: 1.4.0
    hooks:
      - id: wemake-python-styleguide
        name: WPS Linter
        additional_dependencies:
          - flake8-docstrings
          - flake8-annotations

  # Test coverage check
  - repo: local
    hooks:
      - id: pytest-coverage
        name: Pytest with Coverage (>90%)
        entry: bash -c 'uv run pytest --cov=. --cov-fail-under=90 --cov-report=term-missing -q'
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]

  # Security checks
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        name: Bandit Security Linter
        args: [-c, pyproject.toml]
        additional_dependencies: ["bandit[toml]"]

  # YAML/TOML formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types_or: [yaml, toml, json]

  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: [--maxkb=500]
      - id: check-merge-conflict
      - id: detect-private-key

ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit hooks
  autofix_prs: true
  autoupdate_branch: ""
  autoupdate_commit_msg: "[pre-commit.ci] pre-commit autoupdate"
  autoupdate_schedule: weekly
  skip: [pytest-coverage]
