[project]
name = "ecomet-task-2"
version = "0.1.0"
description = "Task 2: GitHub repositories scraper with rate limiting"
requires-python = ">=3.13"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
